version: '3.8'

services:
  backend:
    build: server/.
    ports:
      - "3000:3000"
    env_file:
      - server/.env
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    build: database/.
    healthcheck:
      test: echo 'use tabooDB' && echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5