version: '3'

services:
  backend:
    build: server/.
    ports:
      - "3000:3000"
    env_file:
      - server/.env
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    build: database/.
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/tabooDB --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  frontend:
    build: taboo/.
    ports:
      - '5173:80'
    depends_on:
      - backend
    env_file:
      - taboo/.env
